
SELECT * FROM TALUNO;

-- ADD COLUNA ESTADO

ALTER TABLE TALUNO ADD ESTADO CHAR(2) DEFAULT 'RS';

ALTER TABLE TALUNO ADD SALARIO NUMBER(8,2) DEFAULT 620;

-- ALTERANDO REGISTROS
UPDATE TALUNO SET
  ESTADO = 'MG'
  WHERE COD_ALUNO = 1;

UPDATE TALUNO SET
  ESTADO = 'SP', SALARIO = 1000
  WHERE COD_ALUNO = 3

UPDATE TALUNO SET
  ESTADO = 'AC', SALARIO = 250
  WHERE COD_ALUNO = 4

COMMIT

-- RESULTADO QUE SEJAM DIFERENTES DE 'RS' E QUE O SALARIO SEJA MENOR QUE 800

SELECT * FROM TALUNO
  WHERE ESTADO != 'RS'
  AND SALARIO <= 800
  ORDER BY SALARIO DESC

SELECT * FROM TALUNO


-- INSERINDO NOVOS RESQUI

INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE)
   VALUES(_ALUNO.NEXTVAL, 'VALOD', 'DOIS IRMAOS')

INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE)
   VALUES(SEQ_ALUNO.NEXTVAL, 'MAIARA', 'GUARULHOS')


UPDATE TALUNO SET
  NOME = 'PEDRO' , SALARIO = 1200
  WHERE COD_ALUNO  = 24


SELECT * FROM TALUNO


SELECT ESTADO, SALARIO FROM TALUNO
  ORDER BY ESTADO, SALARIO DESC

ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE - 1000;

UPDATE TALUNO SET
  NASCIMENTO =  SYSDATE - 7245
  WHERE COD_ALUNO = 1


UPDATE TALUNO SET
  NASCIMENTO =  SYSDATE - 8000
  WHERE COD_ALUNO = 2


SELECT COD_ALUNO, NOME, CIDADE, Trunc(NASCIMENTO) NASCIMENTO
FROM TALUNO


-- OPERAÇÃO NA CLAUSULA WHERE

SELECT COD_ALUNO, TOTAL, DESCONTO + 1000 AS CALCULO
FROM TCONTRATO
  WHERE TOTAL  > =1000
;


UPDATE TCONTRATO SET
  DESCONTO = NULL
  WHERE COD_CONTRATO = 2


-- RETORNANDO VALORES NULOS

SELECT COD_CONTRATO, TOTAL, Nvl(DESCONTO,0) AS DESCONTO
FROM TCONTRATO


SELECT * FROM TCURSO

INSERT INTO TCURSO VALUES (5, 'WINDOWS', 1000, 50)

ALTER TABLE TCURSO ADD PRE_REQ INTEGER
