SELECT * FROM TALUNO;

SELECT * FROM TCONTRATO;

SELECT * FROM TCURSO

SELECT * FROM TITEM

-- INNER JOIN
-- APELIDANDO AS TABELAS
-- FAZENDO APENAS UMA LIGAÇÃO

SELECT ALU.COD_ALUNO, ALU.NOME, CON.COD_ALUNO, CON.TOTAL
  FROM
TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
ORDER BY TOTAL ASC

SELECT  ALU.COD_ALUNO, ALU.NOME AS ALUNO,
        CON.COD_CONTRATO, CON.DATA, CON.TOTAL,
        ITE.COD_CURSO,
        CUR.NOME AS CURSO
FROM
TALUNO ALU, TCONTRATO CON, TITEM ITE, TCURSO CUR

WHERE ALU.COD_ALUNO = CON.COD_ALUNO
AND
CON.COD_CONTRATO = ITE.COD_CONTRATO
AND
ITE.COD_CURSO = CUR.COD_CURSO
ORDER BY CON.TOTAL DESC;






