-- Adicione uma coluna chamada OBSERVACAO na tabela TCONTRATO com o tipo de dado VARCHAR(100)

ALTER TABLE TCONTRATO ADD OBSERVACAO VARCHAR(100)

SELECT * FROM TCONTRATO

-- Renomeie a coluna DESCONTO na tabela TCONTRATO para DESCONTO_APLICADO.

ALTER TABLE TCONTRATO RENAME COLUMN DESCONTO TO DESCONTO_APLICADO

SELECT * FROM TCONTRATO

-- Remova a coluna TESTE da tabela TCONTRATO.

SELECT * FROM TCONTRATO

ALTER TABLE TCONTRATO DROP COLUMN TESTE



