--Crie uma nova tabela chamada TPAGAMENTO com as seguintes colunas:
    --COD_PAGAMENTO (tipo INTEGER, chave primária)
    --DATA_PAGAMENTO (tipo DATE)
    --VALOR_PAGAMENTO (tipo NUMBER(8,2))

CREATE SEQUENCE SEQ_PGT START WITH 1;

CREATE TABLE TPAGAMENTO
(
        COD_PAGAMENTO  INTEGER NOT NULL PRIMARY KEY,
        DATA_PAGAMENTO DATE,
        VALOR_PAGAMENTO NUMBER (8,2)
)

SELECT * FROM TPAGAMENTO;

--Altere a tabela TITEM para adicionar uma coluna QUANTIDADE do tipo INTEGER.

ALTER TABLE TITEM ADD QUANTIDADE INTEGER

SELECT * FROM TITEM

--Remova a coluna COD_CURSO da tabela TITEM

ALTER TABLE TITEM ADD TESTE VARCHAR (10)

SELECT * FROM TITEM



